import { BigInt } from "@graphprotocol/graph-ts";

export const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";

export let BIGINT_ZERO = BigInt.fromI32(0);
export let BIGINT_ONE = BigInt.fromI32(1);

export const LIMIT_ORDER_PENDING = "LIMIT_ORDER_PENDING";
export const OPENING = "OPENING";
export const OPEN = "OPEN";
export const CANCELED = "CANCELED";
export const OPEN_TIMED_OUT = "OPEN_TIMED_OUT";
export const CLOSING = "CLOSING";
export const CLOSE_TIMED_OUT = "CLOSE_TIMED_OUT";
export const CLOSED = "CLOSED";

export const TRADE_STATUS = {
  OPENING,
  LIMIT_ORDER_PENDING,
  OPEN,
  CANCELED,
  OPEN_TIMED_OUT,
  CLOSING,
  CLOSE_TIMED_OUT,
  CLOSED,
};

export const TERMINAL_TRADE_STATES = [CANCELED, OPEN_TIMED_OUT, CLOSED];

export const MARKET_TRADE = "MARKET";
export const LIMIT_ORDER_TRADE = "LIMIT_ORDER";

export const TRADE_TYPE = {
  MARKET_TRADE,
  LIMIT_ORDER_TRADE,
};

export const NONE = "NONE";
export const REQUESTED = "REQUESTED";
export const TIMED_OUT = "TIMED_OUT";
export const RECEIVED = "RECEIVED";

export const PRICE_ORDER_STATUS = {
  NONE,
  REQUESTED,
  TIMED_OUT,
  RECEIVED,
};

export const NETWORKS = {
  POLYGON: "polygon",
  MUMBAI: "mumbai",
};

export const LIMIT_ORDER_TYPE = {
  TP: "TP",
  SL: "SL",
  LIQ: "LIQ",
  OPEN: "OPEN",
};

export const LIMIT_ORDER_TYPE_IX = [
  LIMIT_ORDER_TYPE.TP,
  LIMIT_ORDER_TYPE.SL,
  LIMIT_ORDER_TYPE.LIQ,
  LIMIT_ORDER_TYPE.OPEN,
];

export const OPEN_LIMIT_ORDER_STATUS = {
  OPEN: "OPEN",
  CANCELED: "CANCELED",
  FULFILLED: "FULFILLED",
};

export const PRICE_ORDER_TYPE = {
  MARKET_OPEN: "MARKET_OPEN",
  MARKET_CLOSE: "MARKET_CLOSE",
  LIMIT_OPEN: "LIMIT_OPEN",
  LIMIT_CLOSE: "LIMIT_CLOSE",
  UPDATE_SL: "UPDATE_SL",
};

export const PRICE_ORDER_TYPE_IX = [
  PRICE_ORDER_TYPE.MARKET_OPEN,
  PRICE_ORDER_TYPE.MARKET_CLOSE,
  PRICE_ORDER_TYPE.LIMIT_OPEN,
  PRICE_ORDER_TYPE.LIMIT_CLOSE,
  PRICE_ORDER_TYPE.UPDATE_SL,
];

export const OPEN_LIMIT_ORDER_TYPE = {
  LEGACY: "LEGACY",
  REVERSAL: "REVERSAL",
  MOMENTUM: "MOMENTUM",
};

export const OPEN_LIMIT_ORDER_TYPE_IX = [
  OPEN_LIMIT_ORDER_TYPE.LEGACY,
  OPEN_LIMIT_ORDER_TYPE.REVERSAL,
  OPEN_LIMIT_ORDER_TYPE.MOMENTUM,
];
