type MarketOrder implements PriceOrder @entity {
  "Generated off-chain ID"
  id: ID!

  "Status of the order"
  status: PriceOrderStatus!

  "Type of order"
  type: PriceOrderType

  "Trade of the order"
  trade: Trade!

  "Block of order execution"
  block: BigInt

  tokenId: Int

  "Asking open price of trade"
  wantedPrice: BigInt!

  "Acceptable percent change between wantedPrice and actual open price"
  slippageP: BigInt!

  "Synthetic spread reduction from NFT ownership"
  spreadReductionP: BigInt!

  "Received order price"
  price: BigInt!

  "Created timestamp"
  createdAtTimestamp: BigInt!

  "Created block number"
  createdAtBlockNumber: BigInt!

  "Order-related transactions"
  transactions: [String!]!
}
