enum LimitOrderType {
  TP
  SL
  LIQ
  OPEN
}

type NftOrder implements PriceOrder @entity {
  "Generated off-chain ID"
  id: ID!

  "Status of the order"
  status: PriceOrderStatus!

  "Type of order"
  type: PriceOrderType

  "NFT order type"
  nftOrderType: LimitOrderType

  "Trade of the order"
  trade: Trade!

  tokenId: Int

  "Holder which triggered order"
  nftHolder: NftHolder!

  "NFT of holder"
  nftId: Int!

  "Received order price"
  price: BigInt!

  "Created timestamp"
  createdAtTimestamp: BigInt!

  "Created block number"
  createdAtBlockNumber: BigInt!
}
