enum PriceOrderStatus {
  NONE
  REQUESTED
  TIMED_OUT
  RECEIVED
}

enum PriceOrderType {
  MARKET_OPEN
  MARKET_CLOSE
  LIMIT_OPEN
  LIMIT_CLOSE
  UPDATE_SL
}

interface PriceOrder {
  "Order ID -- generated on chain"
  id: ID!

  "Status of the order"
  status: PriceOrderStatus!

  "Type of order"
  type: PriceOrderType

  "Trade of the order"
  trade: Trade!

  "TODO"
  tokenId: Int

  "Received price of Trade pairIndex"
  price: BigInt
}
