type SlUpdateOrder implements PriceOrder @entity {
  "Order ID -- generated on chain"
  id: ID!

  "Status of the order"
  status: PriceOrderStatus!

  "Type of order"
  type: PriceOrderType

  "Trade of the order"
  trade: Trade!

  "TODO"
  tokenId: Int

  "Received price of Trade pairIndex"
  price: BigInt

  "Requested updated SL of trade"
  newSl: BigInt
}
