type SlUpdateOrder implements PriceOrder @entity {
  "Generated off-chain ID"
  id: ID!

  "Status of the order"
  status: PriceOrderStatus!

  "Type of order"
  type: PriceOrderType

  "Trade of the order"
  trade: Trade!

  tokenId: Int

  "Received order price"
  price: BigInt

  "Requested updated SL of trade"
  newSl: BigInt
}
