type Trader @entity {
  "Address of trader"
  id: ID!

  "Address of referral of trader"
  referral: Bytes!

  "Maximum leverage unlocked by trader"
  leverageUnlocked: Int

  "Total rewards of trader"
  referralRewardsTotal: BigInt

  "Created timestamp"
  createdAtTimestamp: BigInt!

  "Created block number"
  createdAtBlockNumber: BigInt!

  "All trades"
  trades: [Trade!] @derivedFrom(field: "trader")
}
