type ContractTradeState @entity {
  id: ID!
  _pendingMarketOrdersLookup: String
  _pendingNftOrdersLookup: String
  _pendingSlUpdateOrdersLookup: String
  _openLimitOrdersLookup: String
  _openTradesLookup: String
  _openTradesInfoLookup: String
}
