type TradeInfo @entity {
  id: ID!
  trade: Trade
  tokenId: Int
  tokenPriceDai: BigInt
  openInterestDai: BigInt
  tpLastUpdated: BigInt
  slLastUpdated: BigInt
  beingMarketClosed: Boolean

  "Created timestamp"
  createdAtTimestamp: BigInt!

  "Created block number"
  createdAtBlockNumber: BigInt!
}
