enum OpenLimitOrderStatus {
  NONE
  OPEN
  CANCELED
  FULFILLED
}

enum OpenLimitOrderType {
  LEGACY
  REVERSAL
  MOMENTUM
}

type OpenLimitOrder @entity {
  "Generated off-chain ID"
  id: ID!

  "Type of open limit order"
  type: OpenLimitOrderType

  "Status of open limit order"
  status: OpenLimitOrderStatus!

  "Trade associated with open limit order"
  trade: Trade!

  "Spread reduction percentage"
  spreadReductionP: BigInt!

  "Min price for limit order execution"
  minPrice: BigInt!

  "Max price for limit order execution"
  maxPrice: BigInt!

  "Block of limit order execution"
  block: BigInt!

  tokenId: Int

  "Executing order"
  nftOrder: NftOrder

  "Created timestamp"
  createdAtTimestamp: BigInt!

  "Created block number"
  createdAtBlockNumber: BigInt!
}
