enum OpenLimitOrderStatus {
  OPEN
  CANCELED
  FULFILLED
}

enum OpenLimitOrderType {
  LEGACY
  REVERSAL
  MOMENTUM
}

type OpenLimitOrder @entity {
  "Generated off-chain ID"
  id: ID!

  "Type of open limit order"
  type: OpenLimitOrderType

  "Status of open limit order"
  status: OpenLimitOrderStatus

  "Trade associated with order"
  trade: Trade!

  "Spread reduction percentage"
  spreadReductionP: BigInt!

  "Min price for LO execution"
  minPrice: BigInt!

  "Max price for LO execution"
  maxPrice: BigInt!

  "Block of LO execution"
  block: BigInt!

  "TODO"
  tokenId: Int

  "Executing order"
  nftOrder: NftOrder
}
